### ISSUE TITLE
Filter fails with undefined error when using a value that comes from a promise that eventually returns a string

### ISSUE THREAD

**Issue by toymachiner62** [konsumer/ngInflection#2]
See this https://github.com/dreamerslab/node.inflection/pull/28. The node.inflection owner thinks this should be handled in this ngInflection wrapper. I'm not sure if there really is a good way to handle this here.

**Comment by konsumer** [comment]
Yeh, I didn't consider promises when making the thin wrapper. I will try to dig in this week.

**Comment by konsumer** [comment]
there ya go! :)

**Comment by toymachiner62** [comment]
Thanks. Are you going to up to push to bower?

**Comment by konsumer** [comment]
updated version tag. In the future, I consider it more polite to issue pull-requests then ask for small changes like null-check-wrapping & tag-increment. Maybe that's just me, but I feel it's like sweetly saying "Oh hey, I use this. Here is this thing I need in easy-to-integrate-code-form. It's probly useful to others." It took all of 10 minutes and this "library" is just the tiniest thing, so no big whoop, but in case you weren't aware of that convention.

**Comment by toymachiner62** [comment]
I try to submit pull requests when I know how to fix the issue. I wasn't too familiar with creating angular filters and didn't know a good way to do it otherwise I would have submitted a PR. I looked at your solution and it makes sense to me now.

**Comment by konsumer** [comment]
ah. fair enough. carry on!

**Comment by konsumer** [comment]
also, that's not to diminish the value of testing edge-cases that I don't have, which is very useful. Lemme know if it doesn't work for you. I hadn't thought of testing with promises.
