### ISSUE TITLE
Guard for missing strings

### ISSUE THREAD

**Issue by Rodeoclash** [konsumer/ngInflection#3]
Just a thought, is it worth guarding for the presence of missing strings in the filters?

If I have a view that is slow/remotely loading data, the filter will throw an error each digest cycle until a value is present. I can prevent this by wrapping my code in an ng-if however it feels more "Angular"\* to be able to have the filter handle missing strings until they are present.
- A good example is the Angular currency filter, it will not error if it's used on an undefined value that is lazily loaded.

**Comment by Rodeoclash** [comment]
Ha! I see you've just done a release which does this. Updating solved it. Thanks for a great plugin :)

**Comment by konsumer** [comment]
:)
