### ISSUE TITLE
Transform does not work as expected.

### ISSUE THREAD

**Issue by blakewest** [konsumer/ngInflection#5]
So, I actually found a use case for the "transform" filter, and that is using it as a piping mechanism when you're using the $filter service, and you aren't in templates. For instance...

```
  filter('manipulateThingFromApi', function($filter) {
    return function(apiThing) {
      //manipulate api things
      return $filter('transform')(apiThing, ['pluralize', 'titleize']);
    }
  }
```

However, this did not work. looking at the source code, I realized why. Using `apply` doesn't make sense for transform because it actually takes an array as an argument. `apply` will pass each filter individually, which makes it do nothing. I'll make a PR. The fix is to just do `inflection.transform(str, arr)`.

**Comment by konsumer** [comment]
Good catch. Merged. Thanks!
