### ISSUE TITLE
Doesn't work with browserify

### ISSUE THREAD

**Issue by pmowrer** [konsumer/ngInflection#8]
Unless both dependencies (`angular` and `inflection`) are provided on the window object, `ngInflection` won't work. This is due to the following two lines:

https://github.com/konsumer/ngInflection/blob/5a56cffa5f8f86be350edfc12a9a82a432ae5955/index.js#L2-3

`window` is always defined in the browser so this library will always require that both deps are in the global scope.

**Comment by konsumer** [comment]
In the browser those lines at least used to use the global-registered inflection & angular that get exposed in bower or script-tags. I will investigate.

**Comment by konsumer** [comment]
Hmm, in a test project, when I do this:

``` js
var angular = require('angular');
console.log(angular);
```

I get `Object {}`.

If I do this:

``` js
require('angular');
console.log(window.angular);
```

I get a proper angular object, so there may be an upstream angular packaging issue with that version.
